name: kataku
version: 1.0.0+1
publish_to: none
description: Kataku Android App
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  audioplayers: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  image_picker: ^0.8.7+4
  path: ^1.8.3
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  video_player: ^2.6.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
